name: tv_remote_controller
description: TV  remote controller

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  flutter_launcher_icons: ^0.8.0
  path_provider: ^1.6.18

dev_dependencies:
  test: ^1.15.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
   - ./base_url.txt

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: 'icon/icon.png'